services:
  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"

  postgres:
    image: postgres:9.6
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: "twins"
      POSTGRES_PASSWORD: ""
      POSTGRES_DB: "twins"
    env_file:
      - ".env"
      - "{{environment}}.env"
    networks:
      default:
        aliases:
          - "postgres"
